# Generated by Django 4.0.5 on 2022-06-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[['Kg', 'Kilogram'], ['Lt', 'Litre']], max_length=20),
        ),
    ]
