# Generated by Django 4.0.5 on 2022-06-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[['Kilogram', 'Kilogram'], ['Litre', 'Litre']], max_length=20),
        ),
    ]
